In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv("customers.csv")
departments = pd.read_csv("departments.csv")
employees = pd.read_csv("employees.csv")
orders = pd.read_csv("orders.csv")
products = pd.read_csv("products.csv")
sales = pd.read_csv("sales.csv")

In [3]:
# Show the department name and average salary of employees in each department, sorted from highest average salary to lowest.
departments.merge(employees, on = "department_id").groupby("department_name")["salary"].mean().sort_values(ascending=False)

department_name
Finance       80000.000000
Operations    70666.666667
Marketing     59500.000000
Sales         58750.000000
Data          55000.000000
HR            51875.000000
Legal         50000.000000
IT            48500.000000
Name: salary, dtype: float64

In [4]:
# Show the product name, total quantity sold, and total revenue generated for each product.
product_order_merge = products.merge(orders, on="product_id")

In [5]:
product_order_merge.head(3)

,product_id,product_name,category,brand,price,stock_quantity,order_id,customer_id,employee_id,quantity,order_amount,order_date,payment_method,order_status
0,1,Laptop,Electronics,Dell,55000.0,25,1,1,103,1,55000.0,2024-01-05,UPI,Delivered
1,1,Laptop,Electronics,Dell,55000.0,25,21,21,103,2,110000.0,2024-01-25,UPI,Delivered
2,1,Laptop,Electronics,Dell,55000.0,25,41,16,103,1,55000.0,2024-02-14,UPI,Delivered

In [6]:
#Q.5 Find the employee who has generated the highest total sales amount from the sales table.

sales.merge(employees, left_on = "employee_id", right_on = "employee_id").groupby("employee_name")["sale_amount"].sum().sort_values(ascending=False).head(1)

employee_name
Aditya Rao    382900.0
Name: sale_amount, dtype: float64

In [7]:
#Q.6 Show the city-wise count of customers and sort it from highest to lowest.
customers["city"].value_counts(ascending=False)

city
Mumbai        4
Pune          3
Delhi         3
Bangalore     2
Chennai       2
Hyderabad     2
Ahmedabad     1
Noida         1
Surat         1
Lucknow       1
Kolkata       1
Jaipur        1
Indore        1
Patna         1
Chandigarh    1
Name: count, dtype: int64

In [8]:
# Find the products whose stock quantity is less than 20 and price is greater than 1000.
products[(products["stock_quantity"] < 20) & (products["price"] > 1000)] [["product_name", "price", "stock_quantity"]]

    product_name    price  stock_quantity
9         Camera  45000.0              15
15     Projector  38000.0              12
19  Gaming Chair  15000.0              18

In [15]:
# Show the monthly total order amount for all orders placed in 2025.
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [30]:
orders[(orders['order_date'].dt.year == 2024)]

,order_id,customer_id,product_id,employee_id,quantity,order_amount,order_date,payment_method,order_status
0,1,1,1,103,1,55000.0,2024-01-05,UPI,Delivered
1,2,2,2,111,2,2400.0,2024-01-06,Credit Card,Delivered
2,3,3,3,119,1,2500.0,2024-01-07,Debit Card,Shipped
3,4,4,4,127,1,18000.0,2024-01-08,Cash,Processing
4,5,5,5,103,2,19000.0,2024-01-09,UPI,Delivered
...,...,...,...,...,...,...,...,...,...
95,96,21,16,103,1,38000.0,2024-04-09,UPI,Shipped
96,97,22,17,111,2,18000.0,2024-04-10,Credit Card,Delivered
97,98,23,18,119,5,9000.0,2024-04-11,Debit Card,Delivered
98,99,24,19,127,2,1000.0,2024-04-12,Cash,Processing
99,100,25,20,103,1,15000.0,2024-04-13,UPI,Delivered